missiles:
    SMALLMISSILE:
        speed: 2
        range: 750
        power: 3
        accuracy: 100
    SMALLMISSILEHE:
        speed: 1
        range: 600
        power: 3.5
        accuracy: 120
    SMALLMISSILELR:
        speed: 2
        range: 900
        power: 3
        accuracy: 100
    SMALLMISSILEAC:
        speed: 2
        range: 700
        power: 3
        accuracy: 60
    ANTIAIRMISSILE:
        speed: 5
        range: 600
        power: 4
        accuracy: 0
    MISSILE:
        speed: 2.5
        range: 1000
        power: 4.5
        accuracy: 80
    MISSILEHE:
        speed: 2
        range: 1000
        power: 5
        accuracy: 100
    MISSILELR:
        speed: 2.5
        range: 1500
        power: 4.5
        accuracy: 80
    MISSILEAC:
        speed: 2.5
        range: 1250
        power: 4.5
        accuracy: 16
    MISSILEAPONE:
        speed: 2
        range: 1550
        power: 3.5
        accuracy: 40
    MISSILEAPTWO:
        speed: 2.5
        range: 1700
        power: 4
        accuracy: 20
    MISSILEAPTHR:
        speed: 4
        range: 1850
        power: 4.5
        accuracy: 10
    MISSILEGAS:
        speed: 3
        range: 1600
        power: 0.5
        accuracy: 80
    MISSILEEXCAV:
        speed: 0.5
        range: 100
        power: 14
        accuracy: 50
    MISSILESTICK:
        speed: 4
        range: 1600
        power: 1
        accuracy: 70
    MISSILEICBM:
        speed: 5
        range: 7000
        power: 10
        accuracy: 50
    MISSILECLUSTER:
        speed: 3.5
        range: 1600
        power: 4
        accuracy: 90
    MISSILENAPALM:
        speed: 3
        range: 1600
        power: 2
        accuracy: 80
    MISSILEADV:
        speed: 4
        range: 2000
        power: 4
        accuracy: 40
    MISSILEHEADV:
        speed: 3.5
        range: 2000
        power: 6
        accuracy: 35
    MISSILELRADV:
        speed: 4.5
        range: 2500
        power: 4
        accuracy: 40
    MISSILEACADV:
        speed: 4
        range: 2000
        power: 4.5
        accuracy: 20
    ANTIELYTRAMISSILE:
        speed: 6
        range: 700
        power: 4
        accuracy: 0

mine:
    explosivepower: 8
    # Amount of random damage to apply to the receiving player
    maxranddamage: 10

#set this to the name of a pack in the /lang folder without a .yml
translation-pack: pack-EN
#Dont edit, imports lang packs on first start
saved-packs:
    - pack-EN
    - pack-NL
    - pack-CN
    - pack-TW
    - pack-FR

logging:
    # Sends a message to console on missile shot :O
    logMissileShots: true
    # BROADCASTS TO ALL PLAYERS THAT A MISSILE WAS SHOT
    broadcastMissileShots: false
    # Seconds to wait before broadcasting the missile being shot
    waitTimeBeforeBroadcast: 20

other:
    #How long until cleanup of lost armour stands (ticks)
    cleanup-wait-time: 1200

options:
  auto-update: true
