missiles:
    SMALLMISSILE:
        speed: 2
        range: 500
        power: 3
        accuracy: 100
    SMALLMISSILEHE:
        speed: 1
        range: 400
        power: 3.5
        accuracy: 120
    SMALLMISSILELR:
        speed: 2
        range: 600
        power: 3
        accuracy: 100
    MISSILEAC:
        speed: 2
        range: 550
        power: 3
        accuracy: 60
    ANTIELYTRAMISSILE:
        speed: 6
        range: 700
        power: 4
        accuracy: 0
    ANTIAIRMISSILE:
        speed: 5
        range: 450
        power: 4
        accuracy: 0
    MISSILE:
        speed: 2.5
        range: 650
        power: 4.5
        accuracy: 80
    MISSILEHE:
        speed: 2
        range: 600
        power: 5
        accuracy: 100
    MISSILELR:
        speed: 2.5
        range: 800
        power: 4.5
        accuracy: 80
    MISSILEAC:
        speed: 2.5
        range: 600
        power: 4.5
        accuracy: 50
    MISSILEAPONE:
        speed: 2
        range: 550
        power: 3.5
        accuracy: 40
    MISSILEAPTWO:
        speed: 2.5
        range: 700
        power: 4
        accuracy: 30
    MISSILEAPTHR:
        speed: 3
        range: 850
        power: 4.5
        accuracy: 20
    MISSILEGAS:
        speed: 3
        range: 600
        power: 0.5
        accuracy: 80
    MISSILEEXCAV:
        speed: 0.5
        range: 100
        power: 8
        accuracy: 50
    MISSILESTICK:
        speed: 4
        range: 600
        power: 1
        accuracy: 70
    MISSILEICBM:
        speed: 5
        range: 3500
        power: 8
        accuracy: 50
    MISSILECLUSTER:
        speed: 3.5
        range: 600
        power: 4
        accuracy: 80
    MISSILENAPALM:
        speed: 3
        range: 600
        power: 2
        accuracy: 140
    MISSILEADV:
        speed: 4
        range: 1000
        power: 4
        accuracy: 40
    MISSILEHEADV:
        speed: 3.5
        range: 1000
        power: 5
        accuracy: 35
    MISSILELRADV:
        speed: 4.5
        range: 1500
        power: 4
        accuracy: 40
    MISSILEACADV:
        speed: 4
        range: 1000
        power: 4.5
        accuracy: 20
mine:
    explosivepower: 8
    # Amount of random damage to apply to the receiving player
    maxranddamage: 10

#set this to the name of a pack in the /lang folder without a .yml
translation-pack: pack-EN
#Dont edit, imports lang packs on first start
saved-packs:
    - pack-EN
    - pack-NL

logging:
    logMissileShots: true

other:
    #How long until cleanup of armour stands (ticks)
    cleanup-wait-time: 1200

options:
  auto-update: true